In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\ashur\Desktop\library\vgsales.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

# Data Understanding

In [3]:
# Total Rows & columns
df.shape

(16598, 11)

In [4]:
# data info 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 1.4 MB

In [5]:
# Null value count in each Columne
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [6]:
# Duplicate count in data    
df.duplicated().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
16593    False
16594    False
16595    False
16596    False
16597    False
Length: 16598, dtype: bool>

In [7]:
print(df.Global_Sales.mean())
print(df.Global_Sales.median())

0.5374406555006629
0.17

In [8]:
""" 1.There is no duplicate rows in data.
    2.some null values are present in Year and Publisher columne ,we have to deal with it.
    3.Data type of each columne is correct. Year columne is in float datatype.
    4.No negative value.
    5.The Global_Sales distribution is Right skewed(mean 0.534 > median 0.17) indicating that a few blockbuster games have
      very high sales while most games have lower sales.
"""

' 1.There is no duplicate rows in data.\n    2.some null values are present in Year and Publisher columne ,we have to deal with it.\n    3.Data type of each columne is correct. Year columne is in float datatype.\n    4.No negative value.\n    5.The Global_Sales distribution is Right skewed(mean 0.534 > median 0.17) indicating that a few blockbuster games have\n      very high sales while most games have lower sales.\n'

# Data Cleaning

In [9]:
# Exact missing values in Year and Publisher columne.
df[["Year","Publisher"]].isnull().sum()

Year         271
Publisher     58
dtype: int64

In [10]:
# To check invalid year like(0,9999 or future year).
df.Year.unique()                                     # No invalid year

array([2006., 1985., 2008., 2009., 1996., 1989., 1984., 2005., 1999.,
       2007., 2010., 2013., 2004., 1990., 1988., 2002., 2001., 2011.,
       1998., 2015., 2012., 2014., 1992., 1997., 1993., 1994., 1982.,
       2003., 1986., 2000.,   nan, 1995., 2016., 1991., 1981., 1987.,
       1980., 1983., 2020., 2017.])

In [ ]:
""" filtering the rows with missing year and Publisher value to determune importance if they represent only a small portion 
    of the dataset and cannot be realiably recovered,removing them is the better option."""

In [11]:
df[df.Year.isna()].head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
624,625,Rock Band,X360,NaN,Misc,Electronic Arts,1.93,0.34,0.00,0.21,2.48
649,650,Frogger's Adventures: Temple of the Frog,GBA,NaN,Adventure,Konami Digital Entertainment,2.15,0.18,0.00,0.07,2.39
652,653,LEGO Indiana Jones: The Original Adventures,Wii,NaN,Action,LucasArts,1.54,0.63,0.00,0.22,2.39
711,713,Call of Duty 3,Wii,NaN,Shooter,Activision,1.19,0.84,0.00,0.23,2.26
782,784,Rock Band,Wii,NaN,Misc,MTV Games,1.35,0.56,0.00,0.20,2.11

In [12]:
df[df.Year.isna() & df.Publisher.isna()].sample(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
14087,14089,Housekeeping,DS,NaN,Action,NaN,0.00,0.00,0.04,0.00,0.04
16198,16201,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,Misc,NaN,0.00,0.00,0.01,0.00,0.01
5302,5304,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,NaN,Action,NaN,0.15,0.05,0.14,0.01,0.35
7351,7353,Yu Yu Hakusho: Dark Tournament,PS2,NaN,Fighting,NaN,0.10,0.08,0.00,0.03,0.21
15261,15264,Mario Tennis,3DS,NaN,Sports,NaN,0.00,0.00,0.02,0.00,0.02
1303,1305,Triple Play 99,PS,NaN,Sports,NaN,0.81,0.55,0.00,0.10,1.46
13962,13964,World of Tanks,X360,NaN,Shooter,NaN,0.00,0.03,0.00,0.00,0.04
13672,13674,B.L.U.E.: Legend of Water,PS,NaN,Adventure,NaN,0.00,0.00,0.04,0.00,0.04
16191,16194,Homeworld Remastered Collection,PC,NaN,Strategy,NaN,0.00,0.01,0.00,0.00,0.01
10494,10496,Atsumare! Power Pro Kun no DS Koushien,DS,NaN,Sports,NaN,0.00,0.00,0.10,0.00,0.10

In [13]:
df[df.Year.isna() & df.Publisher.isna()].shape[0]

22

In [14]:
df=df.dropna(subset=["Publisher"])

In [15]:
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            249
Genre             0
Publisher         0
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [ ]:
""" 1. missing value handling      ==> 1.Year missing value      => 271 (1.63 % )
                                       2.Publisher MV            => 58  (0.35 % )
                                       3.Null in both Year & pub => 22  
    
    2. Removed rows with missing Publisher ,as they represent only 0.35 % of the dataset.
    3. Rows with missing year were retained because they still contain valid sales data.
    4. these rows will be excluded only from year-based analysis to aviod baised insights.
"""

# EDA [Exploratory Data Analysis]

In [16]:
# Total Number Of Games.
df.Name.nunique()

11442

In [17]:
# Total Number Of Platforms.
df.Platform.nunique()

31

In [18]:
# Total Number Of Genres.
df.Genre.nunique()

12

In [19]:
# Total Number Of Publishers.
df.Publisher.nunique()

578

In [20]:
# Top 10 Games By Global sales.
df[["Name","Global_Sales"]].sort_values(by="Global_Sales",ascending=False).head(10)

                        Name  Global_Sales
0                 Wii Sports         82.74
1          Super Mario Bros.         40.24
2             Mario Kart Wii         35.82
3          Wii Sports Resort         33.00
4   Pokemon Red/Pokemon Blue         31.37
5                     Tetris         30.26
6      New Super Mario Bros.         30.01
7                   Wii Play         29.02
8  New Super Mario Bros. Wii         28.62
9                  Duck Hunt         28.31

In [21]:
# Top 10 Platform by total Global Sales.
df[["Platform","Global_Sales"]].head(10)

  Platform  Global_Sales
0      Wii         82.74
1      NES         40.24
2      Wii         35.82
3      Wii         33.00
4       GB         31.37
5       GB         30.26
6       DS         30.01
7      Wii         29.02
8      Wii         28.62
9      NES         28.31

In [22]:
# Top 10 Publisher By Global Sales.
df[["Publisher","Global_Sales"]].head(10)

  Publisher  Global_Sales
0  Nintendo         82.74
1  Nintendo         40.24
2  Nintendo         35.82
3  Nintendo         33.00
4  Nintendo         31.37
5  Nintendo         30.26
6  Nintendo         30.01
7  Nintendo         29.02
8  Nintendo         28.62
9  Nintendo         28.31

In [23]:
# Genre Wise Total Global Sales.
df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False)

Genre
Action          1750.33
Sports          1329.35
Shooter         1037.32
Role-Playing     927.31
Platform         830.87
Misc             802.15
Racing           732.03
Fighting         445.70
Simulation       391.96
Puzzle           244.94
Adventure        238.77
Strategy         174.83
Name: Global_Sales, dtype: float64

In [24]:
# Region Wise Total Sales(NA,EU,JP,OTHER).
df[["NA_Sales","EU_Sales","JP_Sales","Other_Sales"]].sum()

NA_Sales       4384.41
EU_Sales       2429.45
JP_Sales       1290.09
Other_Sales     797.08
dtype: float64

In [25]:
# Year-Wise Global Sales Trend.
year_sales=(df[df.Year.notna()].groupby("Year")["Global_Sales"].sum())
print(year_sales,end=" ")

Year
1980.0     11.38
1981.0     35.77
1982.0     28.86
1983.0     16.79
1984.0     50.36
1985.0     53.94
1986.0     37.07
1987.0     21.74
1988.0     47.22
1989.0     73.45
1990.0     49.39
1991.0     32.23
1992.0     76.16
1993.0     45.98
1994.0     79.17
1995.0     88.11
1996.0    199.15
1997.0    200.98
1998.0    256.47
1999.0    251.27
2000.0    201.56
2001.0    331.47
2002.0    395.52
2003.0    357.85
2004.0    414.01
2005.0    458.51
2006.0    521.04
2007.0    609.92
2008.0    678.90
2009.0    667.30
2010.0    600.29
2011.0    515.80
2012.0    363.49
2013.0    368.11
2014.0    337.03
2015.0    264.44
2016.0     70.90
2017.0      0.05
2020.0      0.29
Name: Global_Sales, dtype: float64

In [26]:
# Platform-Wise Sales Trend.
platform_sales=df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(5)
platform_sales

Platform
PS2     1252.43
X360     979.89
PS3      957.29
Wii      926.36
DS       822.19
Name: Global_Sales, dtype: float64

In [27]:
# Top 10 Genres By Average Global Sales.
df.groupby("Genre")["Global_Sales"].mean().sort_values(ascending=False).head(10)

Genre
Platform        0.939898
Shooter         0.793058
Role-Playing    0.624031
Racing          0.586562
Sports          0.567371
Action          0.528960
Fighting        0.526832
Misc            0.468546
Simulation      0.454183
Puzzle          0.421583
Name: Global_Sales, dtype: float64

In [28]:
# Top 10 Publishers By Number Of Games Released.
df.Publisher.value_counts().head(10)

Publisher
Electronic Arts                 1351
Activision                       975
Namco Bandai Games               932
Ubisoft                          921
Konami Digital Entertainment     832
THQ                              715
Nintendo                         703
Sony Computer Entertainment      683
Sega                             639
Take-Two Interactive             413
Name: count, dtype: int64

In [29]:
# Correlation between NA_sales,JP_sales,Other_sales,Global_sales.
df[["NA_Sales","EU_Sales","JP_Sales","Other_Sales","Global_Sales"]].corr()

              NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
NA_Sales      1.000000  0.767672  0.449864     0.634651      0.941036
EU_Sales      0.767672  1.000000  0.435658     0.726326      0.902817
JP_Sales      0.449864  0.435658  1.000000     0.290150      0.611893
Other_Sales   0.634651  0.726326  0.290150     1.000000      0.748260
Global_Sales  0.941036  0.902817  0.611893     0.748260      1.000000

# Bussiness Insights (VGSales)

### 1.Sales Insights

In [ ]:
1. North America is the largest video game market with total sales of approximately 4384.41 million units
2. Europe is the secong largest market contributing around 2429.45 million units.
3. Japan contributed 1290.09 million units,showing a strong but showing more region specific market.
4. Other regions recorded the lowest total sales (797.08 million units)

### 2. Top Selling Games

In [ ]:
5. Wii Sports is the highest-selling game in the dataset.
6. Nintendo titles dominate the list of top-selling games,indicating the company strong market presence.

### 3. Platform & Publisher Insights

In [ ]:
7. PS2 generated the highest total global sales,contributing the largest share of overall revenue.
8. Ninetendo achieved the highest total global sales ,demostrating consistent commercial success.
9. Electronic Arts released the highest number of games.indicating a strong presence in the gaming industry.

### 4. Genre Insights.

In [ ]:
10. The genre with highest total global sales was "Action" ,making it the most popular genre among gamers.
11. the genre with highest average global sales was "Platform",indicating that games in this category generally performed better per title.

### 5. Correlation Insights

In [ ]:
12. Global Sales have the strongest correlation with North America Sales (0.94).
13. Europe Sales also show a strong positive correlation with Global Sales (0.90).
14. Japan sales have a comparatively weaker correlation (0.61) suggesting regional differences in gaming preferences.
15. ALL regional sales show postive correlations with Global Sales.

###  6. Year Wise Insights

In [ ]:
16. Video game sales showed steady  growth from the late 1990s to 2008.
17. Global sales peaked in 2008 reaching approx 670.90 million units,making it the best perfoming year.
18. 2009 also recorded very high sales (667.30 Million units) indicating strong market.
19. after 2009 global sales gradually declined ,with a noticeable decrease from 2010 onward.
20. Recent years (2017 to 2020) show very low sales due to incomplete data .